# CMake generated Testfile for 
# Source directory: C:/Users/i-tem/Documents/dev/xreal-spatial-display
# Build directory: C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-desktop-capture-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-desktop-capture-tests.exe")
  set_tests_properties([=[xreal-desktop-capture-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;473;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-desktop-capture-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-desktop-capture-tests.exe")
  set_tests_properties([=[xreal-desktop-capture-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;473;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-desktop-capture-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-desktop-capture-tests.exe")
  set_tests_properties([=[xreal-desktop-capture-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;473;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-desktop-capture-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-desktop-capture-tests.exe")
  set_tests_properties([=[xreal-desktop-capture-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;473;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-desktop-capture-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-display-topology-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-display-topology-tests.exe")
  set_tests_properties([=[xreal-display-topology-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;493;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-display-topology-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-display-topology-tests.exe")
  set_tests_properties([=[xreal-display-topology-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;493;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-display-topology-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-display-topology-tests.exe")
  set_tests_properties([=[xreal-display-topology-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;493;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-display-topology-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-display-topology-tests.exe")
  set_tests_properties([=[xreal-display-topology-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;493;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-display-topology-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-interface-probe-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-interface-probe-tests.exe")
  set_tests_properties([=[xreal-interface-probe-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;513;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-interface-probe-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-interface-probe-tests.exe")
  set_tests_properties([=[xreal-interface-probe-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;513;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-interface-probe-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-interface-probe-tests.exe")
  set_tests_properties([=[xreal-interface-probe-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;513;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-interface-probe-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-interface-probe-tests.exe")
  set_tests_properties([=[xreal-interface-probe-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;513;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-interface-probe-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-imu-packet-decoder-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-imu-packet-decoder-tests.exe")
  set_tests_properties([=[xreal-imu-packet-decoder-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;533;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-imu-packet-decoder-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-imu-packet-decoder-tests.exe")
  set_tests_properties([=[xreal-imu-packet-decoder-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;533;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-imu-packet-decoder-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-imu-packet-decoder-tests.exe")
  set_tests_properties([=[xreal-imu-packet-decoder-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;533;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-imu-packet-decoder-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-imu-packet-decoder-tests.exe")
  set_tests_properties([=[xreal-imu-packet-decoder-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;533;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-imu-packet-decoder-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-imu-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-imu-calibration-tests.exe")
  set_tests_properties([=[xreal-imu-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;553;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-imu-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-imu-calibration-tests.exe")
  set_tests_properties([=[xreal-imu-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;553;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-imu-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-imu-calibration-tests.exe")
  set_tests_properties([=[xreal-imu-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;553;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-imu-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-imu-calibration-tests.exe")
  set_tests_properties([=[xreal-imu-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;553;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-imu-calibration-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-accelerometer-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-accelerometer-calibration-tests.exe")
  set_tests_properties([=[xreal-accelerometer-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;573;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-accelerometer-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-accelerometer-calibration-tests.exe")
  set_tests_properties([=[xreal-accelerometer-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;573;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-accelerometer-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-accelerometer-calibration-tests.exe")
  set_tests_properties([=[xreal-accelerometer-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;573;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-accelerometer-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-accelerometer-calibration-tests.exe")
  set_tests_properties([=[xreal-accelerometer-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;573;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-accelerometer-calibration-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-bias-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-bias-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-bias-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;596;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-bias-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-bias-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-bias-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;596;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-bias-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-bias-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-bias-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;596;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-bias-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-bias-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-bias-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;596;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-bias-calibration-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-imu-diagnostic-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-imu-diagnostic-options-tests.exe")
  set_tests_properties([=[xreal-imu-diagnostic-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;619;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-imu-diagnostic-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-imu-diagnostic-options-tests.exe")
  set_tests_properties([=[xreal-imu-diagnostic-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;619;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-imu-diagnostic-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-imu-diagnostic-options-tests.exe")
  set_tests_properties([=[xreal-imu-diagnostic-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;619;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-imu-diagnostic-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-imu-diagnostic-options-tests.exe")
  set_tests_properties([=[xreal-imu-diagnostic-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;619;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-imu-diagnostic-options-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-scale-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-scale-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-scale-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;642;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-scale-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-scale-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-scale-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;642;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-scale-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-scale-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-scale-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;642;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-scale-calibration-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-scale-calibration-tests.exe")
  set_tests_properties([=[xreal-gyroscope-scale-calibration-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;642;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-scale-calibration-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyro-scale-calibration-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyro-scale-calibration-options-tests.exe")
  set_tests_properties([=[xreal-gyro-scale-calibration-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;665;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyro-scale-calibration-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyro-scale-calibration-options-tests.exe")
  set_tests_properties([=[xreal-gyro-scale-calibration-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;665;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyro-scale-calibration-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyro-scale-calibration-options-tests.exe")
  set_tests_properties([=[xreal-gyro-scale-calibration-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;665;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyro-scale-calibration-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyro-scale-calibration-options-tests.exe")
  set_tests_properties([=[xreal-gyro-scale-calibration-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;665;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyro-scale-calibration-options-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-recording-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-recording-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-recording-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;688;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-recording-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-recording-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-recording-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;688;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-recording-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-recording-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-recording-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;688;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-recording-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-recording-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-recording-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;688;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-recording-analysis-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-offline-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-offline-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-offline-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;711;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-offline-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-offline-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-offline-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;711;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-offline-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-offline-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-offline-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;711;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-offline-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-offline-analysis-tests.exe")
  set_tests_properties([=[xreal-gyroscope-offline-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;711;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-offline-analysis-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyro-recording-analyzer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyro-recording-analyzer-options-tests.exe")
  set_tests_properties([=[xreal-gyro-recording-analyzer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;734;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyro-recording-analyzer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyro-recording-analyzer-options-tests.exe")
  set_tests_properties([=[xreal-gyro-recording-analyzer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;734;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyro-recording-analyzer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyro-recording-analyzer-options-tests.exe")
  set_tests_properties([=[xreal-gyro-recording-analyzer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;734;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyro-recording-analyzer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyro-recording-analyzer-options-tests.exe")
  set_tests_properties([=[xreal-gyro-recording-analyzer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;734;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyro-recording-analyzer-options-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-physical-units-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-physical-units-tests.exe")
  set_tests_properties([=[xreal-gyroscope-physical-units-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;757;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-physical-units-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-physical-units-tests.exe")
  set_tests_properties([=[xreal-gyroscope-physical-units-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;757;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-physical-units-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-physical-units-tests.exe")
  set_tests_properties([=[xreal-gyroscope-physical-units-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;757;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-physical-units-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-physical-units-tests.exe")
  set_tests_properties([=[xreal-gyroscope-physical-units-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;757;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-physical-units-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-gyroscope-orientation-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-gyroscope-orientation-tests.exe")
  set_tests_properties([=[xreal-gyroscope-orientation-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;780;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-gyroscope-orientation-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-gyroscope-orientation-tests.exe")
  set_tests_properties([=[xreal-gyroscope-orientation-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;780;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-gyroscope-orientation-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-gyroscope-orientation-tests.exe")
  set_tests_properties([=[xreal-gyroscope-orientation-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;780;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-gyroscope-orientation-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-gyroscope-orientation-tests.exe")
  set_tests_properties([=[xreal-gyroscope-orientation-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;780;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-gyroscope-orientation-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-orientation-fusion-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-orientation-fusion-tests.exe")
  set_tests_properties([=[xreal-orientation-fusion-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;803;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-orientation-fusion-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-orientation-fusion-tests.exe")
  set_tests_properties([=[xreal-orientation-fusion-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;803;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-orientation-fusion-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-orientation-fusion-tests.exe")
  set_tests_properties([=[xreal-orientation-fusion-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;803;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-orientation-fusion-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-orientation-fusion-tests.exe")
  set_tests_properties([=[xreal-orientation-fusion-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;803;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-orientation-fusion-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-orientation-comparison-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-orientation-comparison-tests.exe")
  set_tests_properties([=[xreal-orientation-comparison-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;826;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-orientation-comparison-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-orientation-comparison-tests.exe")
  set_tests_properties([=[xreal-orientation-comparison-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;826;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-orientation-comparison-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-orientation-comparison-tests.exe")
  set_tests_properties([=[xreal-orientation-comparison-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;826;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-orientation-comparison-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-orientation-comparison-tests.exe")
  set_tests_properties([=[xreal-orientation-comparison-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;826;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-orientation-comparison-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-orientation-prediction-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-orientation-prediction-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;849;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-orientation-prediction-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-orientation-prediction-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;849;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-orientation-prediction-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-orientation-prediction-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;849;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-orientation-prediction-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-orientation-prediction-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;849;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-orientation-prediction-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-orientation-prediction-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-orientation-prediction-analysis-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;872;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-orientation-prediction-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-orientation-prediction-analysis-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;872;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-orientation-prediction-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-orientation-prediction-analysis-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;872;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-orientation-prediction-analysis-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-orientation-prediction-analysis-tests.exe")
  set_tests_properties([=[xreal-orientation-prediction-analysis-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;872;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-orientation-prediction-analysis-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-orientation-analyzer-missing-file-test]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-orientation-analyzer.exe" "--evaluate-orientation-prediction" "--prediction-input-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/orientation-prediction-missing.csv" "--prediction-horizons-ms" "0,5,10" "--prediction-mode" "constant-velocity" "--prediction-evaluation-json" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.json" "--prediction-evaluation-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.csv")
  set_tests_properties([=[xreal-orientation-analyzer-missing-file-test]=] PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;877;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-orientation-analyzer-missing-file-test]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-orientation-analyzer.exe" "--evaluate-orientation-prediction" "--prediction-input-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/orientation-prediction-missing.csv" "--prediction-horizons-ms" "0,5,10" "--prediction-mode" "constant-velocity" "--prediction-evaluation-json" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.json" "--prediction-evaluation-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.csv")
  set_tests_properties([=[xreal-orientation-analyzer-missing-file-test]=] PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;877;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-orientation-analyzer-missing-file-test]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-orientation-analyzer.exe" "--evaluate-orientation-prediction" "--prediction-input-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/orientation-prediction-missing.csv" "--prediction-horizons-ms" "0,5,10" "--prediction-mode" "constant-velocity" "--prediction-evaluation-json" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.json" "--prediction-evaluation-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.csv")
  set_tests_properties([=[xreal-orientation-analyzer-missing-file-test]=] PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;877;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-orientation-analyzer-missing-file-test]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-orientation-analyzer.exe" "--evaluate-orientation-prediction" "--prediction-input-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/orientation-prediction-missing.csv" "--prediction-horizons-ms" "0,5,10" "--prediction-mode" "constant-velocity" "--prediction-evaluation-json" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.json" "--prediction-evaluation-csv" "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/unused-prediction.csv")
  set_tests_properties([=[xreal-orientation-analyzer-missing-file-test]=] PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;877;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-orientation-analyzer-missing-file-test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-rendering-math-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-rendering-math-tests.exe")
  set_tests_properties([=[xreal-rendering-math-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;907;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-rendering-math-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-rendering-math-tests.exe")
  set_tests_properties([=[xreal-rendering-math-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;907;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-rendering-math-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-rendering-math-tests.exe")
  set_tests_properties([=[xreal-rendering-math-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;907;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-rendering-math-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-rendering-math-tests.exe")
  set_tests_properties([=[xreal-rendering-math-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;907;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-rendering-math-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-renderer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-renderer-options-tests.exe")
  set_tests_properties([=[xreal-renderer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;929;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-renderer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-renderer-options-tests.exe")
  set_tests_properties([=[xreal-renderer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;929;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-renderer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-renderer-options-tests.exe")
  set_tests_properties([=[xreal-renderer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;929;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-renderer-options-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-renderer-options-tests.exe")
  set_tests_properties([=[xreal-renderer-options-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;929;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-renderer-options-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-render-diagnostics-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-render-diagnostics-tests.exe")
  set_tests_properties([=[xreal-render-diagnostics-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;951;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-render-diagnostics-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-render-diagnostics-tests.exe")
  set_tests_properties([=[xreal-render-diagnostics-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;951;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-render-diagnostics-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-render-diagnostics-tests.exe")
  set_tests_properties([=[xreal-render-diagnostics-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;951;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-render-diagnostics-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-render-diagnostics-tests.exe")
  set_tests_properties([=[xreal-render-diagnostics-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;951;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-render-diagnostics-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-multi-panel-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-multi-panel-tests.exe")
  set_tests_properties([=[xreal-multi-panel-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;968;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-multi-panel-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-multi-panel-tests.exe")
  set_tests_properties([=[xreal-multi-panel-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;968;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-multi-panel-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-multi-panel-tests.exe")
  set_tests_properties([=[xreal-multi-panel-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;968;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-multi-panel-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-multi-panel-tests.exe")
  set_tests_properties([=[xreal-multi-panel-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;968;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-multi-panel-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-virtual-display-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-virtual-display-tests.exe")
  set_tests_properties([=[xreal-virtual-display-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;985;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-virtual-display-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-virtual-display-tests.exe")
  set_tests_properties([=[xreal-virtual-display-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;985;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-virtual-display-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-virtual-display-tests.exe")
  set_tests_properties([=[xreal-virtual-display-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;985;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-virtual-display-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-virtual-display-tests.exe")
  set_tests_properties([=[xreal-virtual-display-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;985;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-virtual-display-tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[xreal-virtual-display-driver-model-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Debug/xreal-virtual-display-driver-model-tests.exe")
  set_tests_properties([=[xreal-virtual-display-driver-model-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;1002;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[xreal-virtual-display-driver-model-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/Release/xreal-virtual-display-driver-model-tests.exe")
  set_tests_properties([=[xreal-virtual-display-driver-model-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;1002;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[xreal-virtual-display-driver-model-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/MinSizeRel/xreal-virtual-display-driver-model-tests.exe")
  set_tests_properties([=[xreal-virtual-display-driver-model-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;1002;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[xreal-virtual-display-driver-model-tests]=] "C:/Users/i-tem/Documents/dev/xreal-spatial-display/build-msvc-x64/RelWithDebInfo/xreal-virtual-display-driver-model-tests.exe")
  set_tests_properties([=[xreal-virtual-display-driver-model-tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;1002;add_test;C:/Users/i-tem/Documents/dev/xreal-spatial-display/CMakeLists.txt;0;")
else()
  add_test([=[xreal-virtual-display-driver-model-tests]=] NOT_AVAILABLE)
endif()
subdirs("third_party/hidapi")
